### ISSUE TITLE
Remove /static router and unused /rooms, /users APIs

### ISSUE THREAD

**Issue by withSang** [sparcs-kaist/taxi-back#106]
# Summary 

택시 서비스에서 사용하는 모든 이미지들을 S3에 업로드하게 되면서 기존에 백엔드 서버에 저장된 프로필 사진을 제공하던 /static 라우터의 필요가 없어졌습니다.
또한 어드민 페이지를 추가하면서 `/users/getAllUsers`와 같은 테스트용 API의 필요가 없어졌으므로 이들을 지우려고 합니다.
또한 프론트엔드에서 더 이상 사용되지 않는 오래된 Room API (일명 `v1` API)를 삭제하고, `/rooms/`로 접근하든 `/rooms/v2`로 접근하든 무조건 새로운 Room API를 호출하도록 변경합니다.

# Tasks 

- [x] /static 라우터 제거
- [x] /users, /rooms에서 쓰이지 않는 라우터 제거
- [x] /rooms 로 접속해도 무조건 새로운 방 API(일명 `v2` API)가 호출되도록 하기

**Comment by withSang** [comment]
열린 PR들 몇 개 끝나는 대로 이 이슈에 대한 PR을 열도록 하겠습니다.
