### ISSUE TITLE
메인으로 머지시 새로운 release 생성 및 Docker 이미지를 ecr에 push

### ISSUE THREAD

**Issue by ptptsw** [sparcs-kaist/taxi-back#137]
# Summary 

메인으로 머지시 새로운 release 생성 및 Docker 이미지를 ecr에 push

# Tasks 

- [x] 먼저 main 브랜치에 대해 ci/cd 생성
- [ ] main, dev 브랜치 분리 
- [x] main, dev 브랜치에 대해 ci/cd 수정
