### ISSUE TITLE
내 방 리스트의  참여 중인 방, 과거 참여 방 나누는 기준 변경

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-back#155]
# Summary 

기존 내 방 리스트의 참여 중인 방과 과거 참여 방을 나누는 기준은,
"모든 방의 인원이 정산을 완료하였음" 입니다.

정산 완료 기준을 방이 아니라 개인 별로 관리를 하도록 수정하며,
"방에서 정산 완료를 하거나 결제 하기를 하였음"으로 수정합니다.

# Tasks 

- [x] room Schema에서 isOver제거
- [x] 기존 내 방 리스트 API 수정

**Comment by withSang** [comment]
search API를 제외한(방 검색 시 각 사용자의 정산 여부가 노출되면 안 됨) 모든 방 관련 api에서
- 요청을 보낸 사용자가 해당 방에 대한 정산/결제를 완료한 경우 true
- 아닌 경우 false를 반환하도록 만들겠습니당

**Comment by withSang** [comment]
현재 문제
- [] 방 생성/참여 시 사용자가 참여중인 방들(`user.room` 배열)의 isOver 속성을 사용하여 참여중인 방 개수를 셈 
- [] 방을 나갈 때 `isOver` 속성을 참조함
-> user나 room DB 구조 변경 없이 수정 가능한지
