### ISSUE TITLE
httpmock으로 리팩토링

### ISSUE THREAD

**Issue by chlehdwon** [sparcs-kaist/taxi-back#225]
# Summary 

테스팅 코드들을 httpmock을 사용하여 리팩토링 합니다

# Tasks 

- [x] locations.js 리팩토링
- [x] logininfo.js 리팩토링
- [x] rooms.js 리팩토링
