### ISSUE TITLE
PNPM Migration

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-back#311]
# Summary 

기존 패키지 매니저인 `npm`을 `pnpm`으로 대체합니다.

# Tasks 

- [ ] NPM 의존성 제거
- [ ] PNPM 셋업
- [ ] gitignore에 package-lock.json 파일 추가
- [ ] PNPM 사용을 강제하는 스크립트 추가
