### ISSUE TITLE
`event/23-chuseok` 초반 구성

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-back#334]
# Summary 

`event/23-chuseok` 의 여러 API 들을 위해 초반 구성을 마칩니다.

API 명세서 : https://www.notion.so/sparcs/BACK-2023-FALL-EVENT-BACKEND-API-INTERFACE-ab0daf9377344efaaf1cbcc8415d90e6?pvs=4

- event_status
    - _id (objectID)
    - uid (objectID - ref.users)
    - event_list (objectID[] - ref.event)
    - credit_amount (int)
- event
    - _id (objectID)
    - name (string)
    - reward_amount (int)
    - max_count (int)
    - expire_at (datetime)
    - is_disabled (bool)
- item
    - _id (objectID)
    - name (string)
    - image_url (string)
    - price (int)
    - description (string)
    - is_disabled (bool)
    - product_amount (int)
    - item_type (int) // 0: 티켓아님, 1:티켓 타입1, 2: 티켓 타입 2, 3: 랜덤박스
    - is_randomitem (bool)
    - random_weight (int)
- transaction
    - _id (objectID)
    - type (enum)
    - amount (int)
    - ref_event_id (objectID)
    - ref_item_id (objectID)
    - comment (string)

# Tasks 

- [ ] DB 스키마 생성
- [ ] 미들웨어 생성 (이벤트 진행 여부를 확인하고 이에 따라 API 반환값이 달라지는)
- [ ] `event/23-chuseok/*` API들을 위한 `route` 파일과 `service` 파일, `docs` 파일 구성
