### ISSUE TITLE
2023 가을학기 추석 홍보 이벤트 위한 `transactions`

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-back#341]
# Summary 

2023 가을학기 추석 홍보 이벤트 위한 `transactions` 이 이루어지도록 몇 API를 수정합니다.

# Tasks 

- [ ] 2명 이상 탑승하고 정산 완료 할 때마다 (최대 3번, 송편 300개)
- [ ] 첫 방 개설 할 때 (송편 100개)
- [ ] 이벤트 기간 첫 로그인 (송편 100개)
- [ ] 광고성 정보 동의 (송편 50개)
- [ ] 닉네임 변경 (송편 50개)
- [ ] 정산하는 사람 (송편 100개)
- [ ] 계좌 등록
- [ ] 송금하기
