### ISSUE TITLE
이벤트 관련 MongoDB Query에 Transactions 도입

### ISSUE THREAD

**Issue by kmc7468** [sparcs-kaist/taxi-back#365]
# Summary 

2023 추석 이벤트와 관련된 MongoDB Query 중, 일부 중요한 Query 여러 개를 Transactions를 이용해 묶어 서비스 안정성을 개선하고자 합니다.

# Tasks 

- [ ] `modules/events/eventHandler`
- [ ] `services/items/getRandomItem`
- [ ] `services/items/purchaseHandler`
- [ ] `../services/rooms/commitPaymentHandler`
- [ ] `../services/rooms/settlementHandler`

**Comment by 14KGun** [comment]
우선순위는 낮습니다 @kmc7468
