### ISSUE TITLE
아이템 관련 API 개선

### ISSUE THREAD

**Issue by kmc7468** [sparcs-kaist/taxi-back#387]
# Summary 

아이템 관련 API를 개선하고자 합니다.

# Tasks 

- [x] `stock` 필드가 0 또는 1만 반환하도록 변경
- [ ] 랜덤박스 확률 로깅 메세지 개선
- [x] 아이템 구매시 재고 없을 때 400 BAD REQUEST 전송
