### ISSUE TITLE
Node.js 버전 18로 올리기

### ISSUE THREAD

**Issue by withSang** [sparcs-kaist/taxi-back#404]
# Summary 

Node.js 16의 지원이 2주 전 중단되었습니다. https://nodejs.org/ko/blog/announcements/nodejs16-eol
OpenSSL 1.1.1 버전의 취약점이 존재하지 않는 Node.js 18에서 taxi-back을 구동할 수 있게 dependency의 버전을 올립니다.

# Tasks 

- [x] 취약한 의존성 버전 올리기
- [x] Node.js 18 이상 버전 강제
- [x] Dockerfile, GitHub Action 워크플로 수정
