### ISSUE TITLE
Mongoose v7로 올리기

### ISSUE THREAD

**Issue by withSang** [sparcs-kaist/taxi-back#412]
# Summary 

Mongoose v6 의존성을 v7로 업데이트합니다.

taxi-back에서 수정이 필요할 것으로 예상되는 breaking change의 목록입니다([Mongoose migration 문서](https://mongoosejs.com/docs/migrating_to_7.html)).
1. `strictQuery` is now false by default. (https://mongoosejs.com/docs/migrating_to_7.html#strictquery)
2.`Doc.remove()` is removed. (https://mongoosejs.com/docs/migrating_to_7.html#strictquery)
	- 놀랍게도 주석처리된 room.remove() 코드가 있읍니다
3. Dropped Callback Support (https://mongoosejs.com/docs/migrating_to_7.html#dropped-callback-support)
	- 기존 Mongoose 사용 코드에서 콜백 패턴이 몇 개 있어, 모두 Promise를 사용한 async-await 형태로 바꾸어야 합니다.

일단은 이거 말고는 없어보여요.
breaking change에 효율적으로 대응하기 위해, #159 이슈가 해결된 이후 시작하려고 했는데, 생각보다 변경점이 예측 가능해서 기존 javascript 코드 베이스에서 바로 올려도 될 것 같습니다(?!)

# Tasks 

- [ ] Mongoose 버전 v7로 올리기
- [ ] breaking change에 해당하는 API를 사용하는 코드들을 모두 변경하기
- [ ] Mongoose를 사용하는 모든 서비스 로직의 functionality 확인하기 -> 필요한데, 가능한가요?! @14KGun
