### ISSUE TITLE
채팅 검증 개선

### ISSUE THREAD

**Issue by chlehdwon** [sparcs-kaist/taxi-back#449]
# Summary 

채팅에서 validation 개선 및 기타 오류를 수정합니다

# Tasks 

- [ ] 버튼을 눌렀을 때 API를 잘못 호출하는 문제 수정 (정산 -> 송금 api, 송금 -> 정산 api)
- [ ] 계좌번호 전송 시, 계좌 전송, 송금 요청 api를 통합
- [ ] 채팅 request validation 재검토 (ex: 빈 문자열이 전송 가능함)
