### ISSUE TITLE
Handle person limit 

### ISSUE THREAD

**Issue by xogustlnx** [sparcs-kaist/taxi-back#47]
# Summary

  person limit 를 도입하여 우선적으로 방이 꽉 찼을 때 invite를 불가하게 만들려고 합니다.

# Tasks

- [x] db 수정(new schema data) // 사실 필요없는거 같습니다. 추가 schema collection 필요 없이 length로 handling 가능할 것 같습니다.
- [ ] room/invite 에서 현재 인원과 person limit 비교 
- [ ] 에러 메세지 핸들링
- [ ] front 와 연동(btn disclickable or alert error)
