### ISSUE TITLE
change standard of Old room

### ISSUE THREAD

**Issue by ptptsw** [sparcs-kaist/taxi-back#50]
# Summary 

기존 과거방기준은 출발시간 기준으로 했었는데,
기준을  정산이 끝난방으로 변경

# Tasks 

- [x] isOver  room schema에 추가
- [x] SearchByUser 에서 방가져올 때 isOver 여부에 따라 done/ongoing response에 추가 
- [x] /abort/ 에서 탑승 시간이 지나고 정산이 안됐을때 사용자가 나갈수 없도록 변경
