### ISSUE TITLE
Create test cases for /logininfo, /rooms

### ISSUE THREAD

**Issue by withSang** [sparcs-kaist/taxi-back#52]
# Summary 

In this issue, I'll **try** to add test cases for `/auth`, `/json/logininfo`, `/users`, `/rooms`, `/static` routers, **except** for chatting APIs.

# Tasks 

- [x] Set up test environment
- [ ] `/auth` test case
- [x] `/json/logininfo` test case
- [x] `/users` test case
- [ ] `/rooms` test case
- [ ] `/static` test case
