### ISSUE TITLE
2024 추석 이벤트

### ISSUE THREAD

**Issue by kmc7468** [sparcs-kaist/taxi-back#536]
# Summary 

2024 추석 이벤트를 준비합니다.

# Tasks 

- [ ] lottery 모듈 활성화
- [ ] 상점 및 리더보드 시스템 수정
- [ ] 출석 시스템 추가
