### ISSUE TITLE
Move profile from local to AWS

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-back#54]
# Summary 
 - Save profile images to AWS S3

# Tasks 

- [x] Make default images
- [x] Save profile images to AWS S3
- [x] Add key values to .env and security.js
