### ISSUE TITLE
24 추석 이벤트 관련 마이너 변경사항

### ISSUE THREAD

**Issue by kmc7468** [sparcs-kaist/taxi-back#540]
# Summary 

24 추석 이벤트 배포 전 반영해야 할 마이너한 태스크입니다.

# Tasks 

- [x] `/items/:itemId` Endpoint에서 `realStock` 필드 전달
- [ ] `/items/leaderboard/:itemId` Endpoint에서 당첨 확률이 같은 경우 순위 계산을 잘못하는 버그 수정
- [x] 퀘스트 정보 업데이트
