### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-back#66]
# Summary 
Edit a README.md

# Tasks 
- [x] Short description of the project
- [x] List of contributors
- [x] Basic setup guide
