### ISSUE TITLE
Prevent crawling and ddos

### ISSUE THREAD

**Issue by 14KGun** [sparcs-kaist/taxi-back#68]
# Summary 
뉴아라 서비스에서 과도한 크롤링 요청으로 인해 피해 사례가 발생
스팍스의 모든 서비스에 대해 대책 방안 도입 필요

# Tasks 
- [x] 모든 요청에 대해 적절한 rate-limit 도입
- [x] robots.txt를 통한 크롤링 거부
- [ ] 서비스 이용 약관에 비정상적인 이용에 대한 정의 및 제재 방법 명시

**Comment by withSang** [comment]
express에 rate-limit 패키지를 붙이면 ip당 요청 수를 제한할 수 있는데, reverse proxy 하에서는 제대로 작동하지 않아서, 저희는 reverse proxy 상에서 rate limit을 설정하는 게 맞다고 생각해요!
일단 런칭 전까지 보류합시당
https://www.npmjs.com/package/express-rate-limit

**Comment by withSang** [comment]
헐 관리자 페이지의 api 요청 rate가 높아서 rate-limit의 영향을 받더라고요.
나중에 이슈 열어서 admin 페이지에 대해서만 rate-limit을 제외해야할 것 같아요!

**Comment by Hyogyeong8** [comment]
> 헐 관리자 페이지의 api 요청 rate가 높아서 rate-limit의 영향을 받더라고요. 나중에 이슈 열어서 admin 페이지에 대해서만 rate-limit을 제외해야할 것 같아요!

오 그렇네요!! 이슈 만들겠습니다!
