### ISSUE TITLE
validate from/to locations

### ISSUE THREAD

**Issue by withSang** [sparcs-kaist/taxi-back#74]
# Summary 

출발지 / 도착지 입력값 검증하기

# Tasks 
- [x] DB에 모든 Locations 저장해두기
    - [x] 한국어, 영어 이름 저장 지원
- [x] rooms 라우터에서 요청에 포함된 Location이 DB에 존재하는지 검사하기 
- [x] 사용 가능한 Locations의 목록을 보여주는 api 만들기(GET /locations)

**Comment by withSang** [comment]
한국어 / 영어 지원을 까먹어서 작업 진행 체크리스트를 초기화했습니다!
